Repository mrjvs/42-webserv, pull requests merged in 2021-04, with the labels that each got.

#50 Parser revamped
  makefile
  resources/example-configs/basic.conf
  src/config/ConfigParser.cpp
  src/includes/server/http/HTTPClientData.hpp
  src/includes/server/http/HTTPParseData.hpp
  src/includes/server/http/HTTPParser.hpp
  src/includes/utils/DataList.hpp
  src/includes/utils/stoi.hpp
  src/includes/utils/toUpper.hpp
  src/main.cpp
  src/server/Server.cpp
  src/server/handlers/StandardHandler.cpp
  src/server/http/HTTPClientData.cpp
  src/server/http/HTTPParseData.cpp
  src/server/http/HTTPParser.cpp
  src/server/http/HTTPResponder.cpp
  src/utils/DataList.cpp
  src/utils/stoi.cpp
  src/utils/toUpper.cpp
  tests/parser/index.js
  tests/parser/parser.conf
  tests/parser/root/index.html
Labels: Subject feature

#54 Proxy
  .gitignore
  makefile
  src/config/blocks/RouteBlock.cpp
  src/includes/config/blocks/RouteBlock.hpp
  src/includes/server/handlers/StandardHandler.hpp
  src/includes/server/http/HTTPClient.hpp
  src/includes/server/http/HTTPClientData.hpp
  src/includes/server/http/HTTPResponder.hpp
  src/includes/server/http/Proxy.hpp
  src/includes/server/http/RequestBuilder.hpp
  src/includes/server/http/ResponseBuilder.hpp
  src/server/Server.cpp
  src/server/communication/TCPListener.cpp
  src/server/handlers/StandardHandler.cpp
  src/server/http/HTTPClient.cpp
  src/server/http/HTTPClientData.cpp
  src/server/http/HTTPParser.cpp
  src/server/http/HTTPResponder.cpp
  src/server/http/Proxy.cpp
  src/server/http/RequestBuilder.cpp
  src/server/http/ResponseBuilder.cpp
  tests/proxy/index.js
  tests/proxy/proxy-test.js
  tests/proxy/proxy.conf
Labels: Bonus feature, Todo

#60 Docker
  .dockerignore
  dockerfile
  resources/example-configs/basic.conf
Labels: Bonus feature

#69 Plugins
  makefile
  src/_includes/config/blocks/RouteBlock.hpp
  src/_includes/plugins/PageGenerator.hpp
  src/_includes/plugins/Plugin.hpp
  src/_includes/server/global/GlobalPlugins.hpp
  src/config/blocks/RouteBlock.cpp
  src/plugins/PageGenerator.cpp
  src/plugins/Plugin.cpp
  src/server/globals.cpp
  src/server/responder/handleError.cpp
  src/server/terminal/TerminalResponder.cpp
Labels: Bonus feature

#71 Makefile update
  CMakeLists.txt
  makefile
Labels: Bonus feature

#70 page 404 generator plugin
  src/_includes/plugins/PageGenerator.hpp
  src/plugins/PageGenerator.cpp
Labels: Bonus feature

#73 jsonStatAPI + terminal commands
  makefile
  src/_includes/plugins/JsonStatAPI.hpp
  src/_includes/plugins/Plugin.hpp
  src/_includes/server/http/JsonBuilder.hpp
  src/_includes/server/terminal/TerminalResponder.hpp
  src/_includes/utils/size_tToString.hpp
  src/plugins/JsonStatAPI.cpp
  src/plugins/Plugin.cpp
  src/server/Server.cpp
  src/server/globals.cpp
  src/server/http/JsonBuilder.cpp
  src/server/responder/serving.cpp
  src/server/terminal/TerminalResponder.cpp
  src/utils/size_tToString.cpp
  tests/cgi/mac-env.cgi
  tests/cgi/root/include.php
  tests/cgi/root/test.php
Labels: Bonus feature
